[package]
name = "algorithms"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
criterion = "0.3.5"
rand = "0.8.4"


[[bench]]
name = "benchmark"
harness = false